services:
  rota-facil-rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rota-facil-rabbitmq
    ports:
      - "5672:5672"   # Porta de dados (AMQP)
      - "15672:15672" # Porta do Painel de Controle (Browser)
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - rota-facil-network

  rota-facil-redis:
    image: redis:7.2-alpine
    container_name: rota-facil-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - rota-facil-network

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./src/main/java/com/rota/facil/gateway_service/observability/otel-collector.config.yaml:/etc/otel-config.yaml
    command: [ "--config=/etc/otel-config.yaml" ]
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - rota-facil-network

  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./src/main/java/com/rota/facil/gateway_service/observability/tempo.config.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"
    networks:
        - rota-facil-network


  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./src/main/java/com/rota/facil/gateway_service/observability/prometheus.config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - rota-facil-network

  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - rota-facil-network

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - rota-facil-network

volumes:
  rabbitmq-data:
  redis-data:

networks:
  rota-facil-network:
    driver: bridge