spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - ${WEB_BASE_URL:http://localhost:3001}
              - ${APP_BASE_URL:http://localhost:8099}
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowed-headers:
              - "*"
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/files/**

        - id: audit-service
          uri: lb://audit-service
          predicates:
            - Path=/audit/**

        - id: transport-service
          uri: lb://transport-service
          predicates:
            - Path=/transports/**

        - id: places-service
          uri: lb://places-service
          predicates:
            - Path=/places/**

        - id: location-service
          uri: lb://location-service
          predicates:
            - Path=/locations/**

        - id: notification-service
          uri: lb://notification-service
          predicates: 
            - Path=/notifications/**
