spring.application.name=gateway-service
server.port=8080

# EUREKA
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8081/eureka}
eureka.client.fetch-registry=true


# RABBIMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:rota-facil}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin}

# RABBITMQ AUTH
rabbitmq.auth.exchange=${RABBITMQ_AUTH_EXCHANGE:auth.events}
# queues
rabbitmq.gateway.user.deleted.queue=${RABBITMQ_GATEWAY_USER_DELETED_QUEUE:gateway.user.deleted.queue}
rabbitmq.gateway.user.email.changed.queue=${RABBITMQ_GATEWAY_USER_EMAIL_CHANGED_QUEUE:gateway.user.email.changed.queue}
# routing keys
rabbitmq.user.deleted.routing.key=${RABBITMQ_USER_DELETED_ROUTING_KEY:user.deleted}
rabbitmq.user.email.changed.routing.key=${RABBITMQ_USER_EMAIL_CHANGED_ROUTING_KEY:user.email.changed}


# REDIS
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:admin}


# SECURITY
security.public.key=${PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoVY6ZetAQrk/aFoH7eGdxGELKnTbWiBxQ/NAmQp2I1JDHO0Ib1X1c1JLpaIlKep46Vn4AW8OwUnTe9cltnBNXjA3C1HllHub+yGmCiusRf0Mg1rcSeSuyvEu0uwYZXh2tnPhKonO+1p0GzaFzxSN63KoWvU9c8lx0Q7hNwYN/snX3Qv4qhOoIxBJFgKVzc6m4PoBI6Gk/OUg3beMiiJ1PmjnWDyKL9KgmIgc0nlg7CsTgmRLVafeRuodJngkQRMObPjqKoBVd099/hWtdjxFz+G7w7HRFiB2m/3Cwoo6Qgy3mq00qRLMqWfwjbj1Y02oSQ/gOiSQPRKBL6/F+pSn3wIDAQAB}


# OBSERVABILITY
# trancing
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# metrics
management.otlp.metrics.export.enabled=true

# collector endpoint
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
logging.level.io.micrometer.tracing=DEBUG
logging.level.org.springframework.cloud.sleuth=DEBUG


# logs
logging.file.name=logs/gateway.log